/*
 * File: app/view/MyPanel4.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel4', {
    extend: 'Ext.Panel',

    config: {
        fullscreen: true,
        style: 'background : white',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '常用連結'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        width: '40%',
                        text: '上一頁',
                           listeners: {
                                tap: function() {
                                        Ext.Viewport.animateActiveItem(0, { type: 'slide', direction: 'right' })

                                }
                            }
                    },
                    {
                        xtype: 'button',
                        ui: '',
                        width: '40%',
                        text: '首頁',
                                                   listeners: {
                                tap: function() {
                                        Ext.Viewport.animateActiveItem(0, { type: 'slide', direction: 'right' })

                                }
                            }

                    }
                ]
            },
            {
                xtype: 'panel',
                height: 50,
                html: '',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'component',
                        html: '電機四 S09882099 王大明',
                        margin: '20px'
                    },
                    {
                        xtype: 'button',
                        width: '',
                        text: '登出'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 150,
                id: 'b2',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b5.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://webs6.nutn.edu.tw/stuAbsent/");

                                }
                            }
                    },
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b6.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("https://ecourse.nutn.edu.tw");

                                }
                            }
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 150,
                margin: '',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b7.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://lib.nutn.edu.tw/");

                                }
                            }
                    },
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b8.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://webnt4.nutn.edu.tw/Stusys/");

                                }
                            }
                    }
                ]
            }
        ]
    }

});