/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        fullscreen: true,
        style: 'background : white',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '國立臺南大學'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        width: '40%',
                        text: '上一頁'
                    },
                    {
                        xtype: 'button',
                        ui: '',
                        width: '40%',
                        text: '首頁'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 50,
                html: '',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'component',
                        html: '電機四 S09882099 王大明',
                        margin: '20px'
                    },
                    {
                        xtype: 'button',
                        width: '',
                        text: '登出'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 150,
                id: 'b1',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b1.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://www2.nutn.edu.tw/gac420/view.asp");

                                }
                            }
                    },
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b2.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://web.nutn.edu.tw/phone.htm");

                                }
                            }
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 150,
                margin: '',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b3.png',
                                                                           listeners: {
                                tap: function() {
                                                     window.open("http://webnt2.nutn.edu.tw/Newspost3/");

                                }
                            }
                            
                    },
                    {
                        xtype: 'image',
                        width: '50%',
                        src: 'b4.png',
                           listeners: {
                                tap: function() {
                                        Ext.Viewport.animateActiveItem(1, { type: 'slide', direction: 'left' })

                                }
                            }
                    }
                ]
            }
        ]
    }

});