/*
 * File: app/view/MyPanel8.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel8', {
    extend: 'Ext.Panel',

    config: {
        fullscreen: true,
        style: 'background : white',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '校園導覽'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        width: '40%',
                        text: '上一頁'
                    },
                    {
                        xtype: 'button',
                        ui: '',
                        width: '40%',
                        text: '首頁'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 50,
                html: '"Facebook"'
            },
            {
                xtype: 'panel',
                height: 150,
                id: 'b3',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                }
            },
            {
                xtype: 'panel',
                height: 150,
                margin: '',
                width: '100%',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                }
            }
        ]
    }

});